#!/usr/bin/perl -s

###
### solo v1.4
### Prevents multiple cron instances from running simultaneously.
###
### Copyright 2006-2008 Timothy Kay
###
### Permission is hereby granted, free of charge, to any person obtaining
### a copy of this software and associated documentation files (the
### "Software"), to deal in the Software without restriction, including
### without limitation the rights to use, copy, modify, merge, publish,
### distribute, sublicense, and/or sell copies of the Software, and to
### permit persons to whom the Software is furnished to do so, subject to
### the following conditions:
###
### The above copyright notice and this permission notice shall be
### included in all copies or substantial portions of the Software.
###
### THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
### EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
### MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
### NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
### LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
### OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
### WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
###

use Socket;

$port =~ /^\d+$/						or die "Usage: $0 -port=PORT COMMAND\n";
$addr = pack(CnC, 127, $<, 1);
print "solo: bind ", join(".", unpack(C4, $addr)), ":$port\n"	if $verbose;

$^F = 10;			# unset close-on-exec

socket(SOLO, PF_INET, SOCK_STREAM, getprotobyname('tcp'))	or die "socket: $!";
bind(SOLO, sockaddr_in($port, $addr))				or $silent? exit: die "solo($port): $!\n";

sleep $sleep if $sleep;

exec @ARGV;
